### ISSUE TITLE
Typo error in ChNilWaitSignal.cpp

### ISSUE THREAD

**Issue by sherikapotein** [greiman/ChNil#5]
Minor one but needs to be addressed nonetheless.
line #20 of the said file may be modified in the repository from
`#include "chNil.h"`
to
`#include "ChNil.h"`

On a side note, I am just starting to dive in the realm of Nil/Chibi and in the same day  i end up stumbling on both your libraries NilRTOS and ChNil. Could you please tell what could be the possible advantages of using ChNil over NilRTOS. I understand that the former is new, but does it improve speeds efficiency, memory signature etc? Just a newbie here

**Comment by greiman** [comment]
I tested on Windows so the lower case 'c' slipped by.

NilRTOS is no longer supported by by Giovanni Di Sirio.  NilRTOS was never really bug free since it was a beta.

ChNil is based on the stable version of Nil.  ChNil has many additional features.  Performance should be similar since the context switch code is identical for both versions of Nil and ChibiOS/RT.
